## `廚師v.s資料分析師`
|  廚師       |       |資料分析師  |
|  ----  | ----  |----  | 
|  採買備料  |**預備階段** |資料清理|
| 櫥櫃      | **存放空間**|資料儲存|
| 廚具 | **使用工具**|分析工具 |
|  廚房 | **環境地點**|運算環境 |
|  料理階段 | **執行階段**| 資料建模分析|
|  擺盤設計 | **結果呈現**|資料視覺化 |
|   上菜| **完成品**|分析結果 |
|  客人 | **需求端**|客戶 |

## `資料分析軟體`
1. 平行運算
    - Zookeeeper
    - Hive 
    - Hbase
    - pig 
    - Mahout 
    - hadoop
    - Storm
    - Apache Spark

2. 資料視覺化
    - Gephi
    - Fusion Tables
    - Dataiku DSS
    - ITALASSI
    - **Tableau**

3. 數值統計計算
    - Waffles
    - octave
    - Weka
    - Stata
    - ELKI
    - matlab
    - Tanagra
    - Alteryx Designer

4. 資料庫
    - Oracle
    - SQL Server
    - Mongo DB
    - My SQL
    - Cloud Spanner
    - Access 資料庫

5. 資料清理
    - OpenRefine
    - datawrange
    - QlikView

6. 基礎程式設計
    - PASCAL
    - SAS
    - perl
    - python
    - Scala
    - Julia
    - R
    - JAVA

## <mark> 玩轉資料

In [1]:
# 多維陣列

[1,2,3,4,5,6]

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [2]:
[1 2 3 4 5 6]

1×6 Matrix{Int64}:
 1  2  3  4  5  6

In [3]:
[1 2 3 ; 4 5 6 ; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [4]:
[1 2 3 4 ; 5 6 7 8 ]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [5]:
A = [1 2 3 4 ; 5 6 7 8 ; 9 10 11 12] 

3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [6]:
A[2,3]

7

In [7]:
A[:,1:2]

3×2 Matrix{Int64}:
 1   2
 5   6
 9  10

In [8]:
A[2:end,2:end]

2×3 Matrix{Int64}:
  6   7   8
 10  11  12

In [9]:
A[:,1:end-1]

3×3 Matrix{Int64}:
 1   2   3
 5   6   7
 9  10  11

#### `矩陣`

In [10]:
A = [1 2 3 ; 4 5 6 ; 7 8 9]
B = [9 8 7 ; 6 5 4 ; 3 2 1]

3×3 Matrix{Int64}:
 9  8  7
 6  5  4
 3  2  1

In [11]:
A+B

3×3 Matrix{Int64}:
 10  10  10
 10  10  10
 10  10  10

In [12]:
A.+B

3×3 Matrix{Int64}:
 10  10  10
 10  10  10
 10  10  10

In [13]:
A*B  # 矩陣相乘 直接用 "*"

3×3 Matrix{Int64}:
  30   24  18
  84   69  54
 138  114  90

In [14]:
eltype(A)

Int64

In [15]:
length(A)

9

In [16]:
ndims(B)

2

In [17]:
size(B)

(3, 3)

In [18]:
a = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [19]:
b=[5,5,5]

3-element Vector{Int64}:
 5
 5
 5

In [20]:
a+b

3-element Vector{Int64}:
 6
 7
 8

In [21]:
a.+b

3-element Vector{Int64}:
 6
 7
 8

In [22]:
a'  # transpose

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  3


\begin{bmatrix}
   a & b& c 
\end{bmatrix}

In [23]:
# broadcast 自動擴展

a'.+b   # 需要 "."  

3×3 Matrix{Int64}:
 6  7  8
 6  7  8
 6  7  8

In [24]:
[a';a';a'] + [b b b]

3×3 Matrix{Int64}:
 6  7  8
 6  7  8
 6  7  8

\
\begin{bmatrix}
    x_{11}       & x_{12} & x_{13} & \dots & x_{1n} \\
    x_{21}       & x_{22} & x_{23} & \dots & x_{2n} \\
    x_{d1}       & x_{d2} & x_{d3} & \dots & x_{dn}
\end{bmatrix}


In [25]:
a'*b

30

In [26]:
a'.*b  

3×3 Matrix{Int64}:
 5  10  15
 5  10  15
 5  10  15

In [27]:
# broadcast 自動擴展
[a';a';a'] .* [b b b]

3×3 Matrix{Int64}:
 5  10  15
 5  10  15
 5  10  15

In [28]:
f(x,y) = 2x+y

f (generic function with 1 method)

In [29]:
f.(a',b)

3×3 Matrix{Int64}:
 7  9  11
 7  9  11
 7  9  11

### `A` 

In [30]:
A

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [31]:
A*B

3×3 Matrix{Int64}:
  30   24  18
  84   69  54
 138  114  90

In [32]:
sum(A)

45

In [33]:
maximum(A)

9

In [34]:
minimum(A)

1

In [35]:
minimum(A,dims=1)

1×3 Matrix{Int64}:
 1  2  3

In [36]:
A=[3 3 3 ; 3 3 3 ; 3 3 3]
accumulate(+,A,dims=1)

3×3 Matrix{Int64}:
 3  3  3
 6  6  6
 9  9  9

In [37]:
accumulate(+,A,dims=2)

3×3 Matrix{Int64}:
 3  6  9
 3  6  9
 3  6  9

In [38]:
cumsum(A,dims=2)

3×3 Matrix{Int64}:
 3  6  9
 3  6  9
 3  6  9

In [39]:
cumprod(A,dims=2)

3×3 Matrix{Int64}:
 3  9  27
 3  9  27
 3  9  27

## `O 矩陣`

In [40]:
zeros(3,5)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [41]:
ones(3,2)

3×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [42]:
ones(Int,3,3)

3×3 Matrix{Int64}:
 1  1  1
 1  1  1
 1  1  1

In [43]:
zeros(Bool,2,2)

2×2 Matrix{Bool}:
 0  0
 0  0

In [44]:
falses(2,3)

2×3 BitMatrix:
 0  0  0
 0  0  0

In [45]:
trues(4,3)

4×3 BitMatrix:
 1  1  1
 1  1  1
 1  1  1
 1  1  1

In [46]:
rand(3,3)

3×3 Matrix{Float64}:
 0.551048  0.247556  0.386813
 0.408066  0.458047  0.629352
 0.333174  0.211848  0.344243

In [47]:
randn(5,2)

5×2 Matrix{Float64}:
 -3.00882   0.785882
  0.310914  0.0620331
  0.52167   0.842477
  1.55913   0.722886
  1.14511   1.60939

In [48]:
fill(520,3,3)

3×3 Matrix{Int64}:
 520  520  520
 520  520  520
 520  520  520

In [49]:
fill("🍌",2,2)

2×2 Matrix{String}:
 "🍌"  "🍌"
 "🍌"  "🍌"

In [50]:
A = zeros(2,2)

fill!(A,818)

2×2 Matrix{Float64}:
 818.0  818.0
 818.0  818.0

In [51]:
X = copy(A)

2×2 Matrix{Float64}:
 818.0  818.0
 818.0  818.0

In [52]:
repeat(A,3)

6×2 Matrix{Float64}:
 818.0  818.0
 818.0  818.0
 818.0  818.0
 818.0  818.0
 818.0  818.0
 818.0  818.0

In [53]:
x = rand(5)

5-element Vector{Float64}:
 0.05684313267016783
 0.8264603537380204
 0.01709841745962326
 0.5018434864992058
 0.1393789315651658

In [54]:
sort(x)

5-element Vector{Float64}:
 0.01709841745962326
 0.05684313267016783
 0.1393789315651658
 0.5018434864992058
 0.8264603537380204

In [55]:
sort(x,rev=true)  # 反轉

5-element Vector{Float64}:
 0.8264603537380204
 0.5018434864992058
 0.1393789315651658
 0.05684313267016783
 0.01709841745962326

In [56]:
x # 未改變 原先的

5-element Vector{Float64}:
 0.05684313267016783
 0.8264603537380204
 0.01709841745962326
 0.5018434864992058
 0.1393789315651658

In [57]:
sort!(x)  # 改變本質

5-element Vector{Float64}:
 0.01709841745962326
 0.05684313267016783
 0.1393789315651658
 0.5018434864992058
 0.8264603537380204

In [58]:
x  # 原陣列 更動

5-element Vector{Float64}:
 0.01709841745962326
 0.05684313267016783
 0.1393789315651658
 0.5018434864992058
 0.8264603537380204

In [59]:
y = randn(6)

6-element Vector{Float64}:
 -1.3564160708828894
 -0.8778685625115491
 -0.26764058831769877
  0.20331605164918556
 -0.21237006724709467
  0.738640710565933

In [60]:
sort(y)

6-element Vector{Float64}:
 -1.3564160708828894
 -0.8778685625115491
 -0.26764058831769877
 -0.21237006724709467
  0.20331605164918556
  0.738640710565933

In [61]:
# 絕對值大小

sort(y,by=abs)

6-element Vector{Float64}:
  0.20331605164918556
 -0.21237006724709467
 -0.26764058831769877
  0.738640710565933
 -0.8778685625115491
 -1.3564160708828894

## `reshape`

In [62]:
reshape(1:12,3,4)

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

## `cat 陣列相接`

In [63]:
a = fill(1,3,3)
b = fill(2,3,3)

3×3 Matrix{Int64}:
 2  2  2
 2  2  2
 2  2  2

In [64]:
cat(a,b,dims=1)

6×3 Matrix{Int64}:
 1  1  1
 1  1  1
 1  1  1
 2  2  2
 2  2  2
 2  2  2

In [65]:
cat(a,b,dims=2)

3×6 Matrix{Int64}:
 1  1  1  2  2  2
 1  1  1  2  2  2
 1  1  1  2  2  2

In [66]:
# horizontal
hcat(a,b)

3×6 Matrix{Int64}:
 1  1  1  2  2  2
 1  1  1  2  2  2
 1  1  1  2  2  2

In [67]:
vcat(a,b)

6×3 Matrix{Int64}:
 1  1  1
 1  1  1
 1  1  1
 2  2  2
 2  2  2
 2  2  2

## <mark> DateFrames

In [68]:
using DataFrames

In [69]:
df = DataFrame(A=1:5,B=["🍎","🍌","🍑","🍇","🍉"])

5×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  🍎
   2 │     2  🍌
   3 │     3  🍑
   4 │     4  🍇
   5 │     5  🍉

In [70]:
df = DataFrame()   # 空白 

0×0 DataFrame

In [71]:
df.A = 1:4

1:4

In [72]:
df.B = ["🍎","🍌","🍑","🍇"]

4-element Vector{String}:
 "🍎"
 "🍌"
 "🍑"
 "🍇"

In [73]:
df

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  🍎
   2 │     2  🍌
   3 │     3  🍑
   4 │     4  🍇

In [74]:
## 預先指定

df = DataFrame(A=Int64[],B=String[],C=Float64[])

0×3 DataFrame
 Row │ A      B       C       
     │ Int64  String  Float64 
─────┴────────────────────────

In [75]:
push!(df,(1,"Ray",5.2))

1×3 DataFrame
 Row │ A      B       C       
     │ Int64  String  Float64 
─────┼────────────────────────
   1 │     1  Ray         5.2

In [76]:
# 字典格式
push!(df,(2,"Lion",3.6))
push!(df,[3,"Tin",6.2])
push!(df,Dict(:A=>4,:B=>"Jay",:C=>2.2))

4×3 DataFrame
 Row │ A      B       C       
     │ Int64  String  Float64 
─────┼────────────────────────
   1 │     1  Ray         5.2
   2 │     2  Lion        3.6
   3 │     3  Tin         6.2
   4 │     4  Jay         2.2

### `由矩陣建立 DataFrame`

In [77]:
mat = [1 "M";2 "F";3 "M" ; 4 "M"]

4×2 Matrix{Any}:
 1  "M"
 2  "F"
 3  "M"
 4  "M"

In [78]:
DataFrame(mat,[:Name,:Gender])

4×2 DataFrame
 Row │ Name  Gender 
     │ Any   Any    
─────┼──────────────
   1 │ 1     M
   2 │ 2     F
   3 │ 3     M
   4 │ 4     M

In [79]:
d = Dict("RayRay"=>[98,99,95],"Lion"=>[78,88,91])

DataFrame(d)

3×2 DataFrame
 Row │ Lion   RayRay 
     │ Int64  Int64  
─────┼───────────────
   1 │    78      98
   2 │    88      99
   3 │    91      95

In [80]:
df = DataFrame(A=1:4,B=["M","F","F","M"])

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  M
   2 │     2  F
   3 │     3  F
   4 │     4  M

In [81]:
# df[:A] -> df[!,:A]
# 修改成
df[!,:A]

4-element Vector{Int64}:
 1
 2
 3
 4

In [82]:
df[!,1]

4-element Vector{Int64}:
 1
 2
 3
 4

In [83]:
df[:,1]

4-element Vector{Int64}:
 1
 2
 3
 4

In [84]:
df.A

4-element Vector{Int64}:
 1
 2
 3
 4

In [85]:
df[1,:]

DataFrameRow
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     1  M

In [86]:
df[1,"A"]

1

In [87]:
df[1,:A]

1

In [88]:
df[1,1]

1

In [89]:
df[1:3,:A]

3-element Vector{Int64}:
 1
 2
 3

In [90]:
df[2:3,[:B,:A]]

2×2 DataFrame
 Row │ B       A     
     │ String  Int64 
─────┼───────────────
   1 │ F           2
   2 │ F           3

In [91]:
df[2:3,[:A,:B]]

2×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     2  F
   2 │     3  F

In [92]:
df[2:3,["A","B"]]

2×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     2  F
   2 │     3  F

In [93]:
df[2:3,1:2]

2×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │     2  F
   2 │     3  F

In [94]:
# change

df[1,:A]=69

69

In [95]:
df

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │    69  M
   2 │     2  F
   3 │     3  F
   4 │     4  M

In [96]:
df[!,:B]=["L","O","V","E"]

4-element Vector{String}:
 "L"
 "O"
 "V"
 "E"

In [97]:
df

4×2 DataFrame
 Row │ A      B      
     │ Int64  String 
─────┼───────────────
   1 │    69  L
   2 │     2  O
   3 │     3  V
   4 │     4  E

## `存檔 .csv`

In [98]:
using CSV

In [99]:
CSV.write("06_csv.csv",df)

"06_csv.csv"

In [100]:
mv("06_csv.csv","ch6_csv.csv")   # 檔案位移及更名

LoadError: ArgumentError: 'ch6_csv.csv' exists. `force=true` is required to remove 'ch6_csv.csv' before moving.

## `讀取CSV`

In [101]:
df = CSV.read("ch6_csv.csv",DataFrame)

4×2 DataFrame
 Row │ A      B       
     │ Int64  String1 
─────┼────────────────
   1 │    69  L
   2 │     2  O
   3 │     3  V
   4 │     4  E

In [102]:
# 讀取外部檔案
df = CSV.read("Korea.csv",DataFrame)

17×3 DataFrame
 Row │ City               share07  total07 
     │ String31?          Int64?   Int64?  
─────┼─────────────────────────────────────
   1 │ Busan               898870  1711418
   2 │ Chungcheongbuk-do   203776   625761
   3 │ Chungcheongnam-do   123054   780517
   4 │ Daegu               679375  1088038
   5 │ Daejeon             133838   598358
   6 │ Gangwon-do          290070   668095
   7 │ Gwangju                720   585716
   8 │ Gyeonggi-do        1760838  4330231
   9 │ Gyeongsangbuk-do    670963  1229173
  10 │ Gyeongsangnam-do    667404  1398804
  11 │ Incheon             409477  1050236
  12 │ Jeju                 95276   237196
  13 │ Jeollabuk-do          1221   854182
  14 │ Jeollanam-do          7869   934821
  15 │ Seoul              1973313  4776870
  16 │ Ulsan               167545   461354
  17 │ missing            missing  missing 

In [103]:
df=df[1:16,:]

16×3 DataFrame
 Row │ City               share07  total07 
     │ String31?          Int64?   Int64?  
─────┼─────────────────────────────────────
   1 │ Busan               898870  1711418
   2 │ Chungcheongbuk-do   203776   625761
   3 │ Chungcheongnam-do   123054   780517
   4 │ Daegu               679375  1088038
   5 │ Daejeon             133838   598358
   6 │ Gangwon-do          290070   668095
   7 │ Gwangju                720   585716
   8 │ Gyeonggi-do        1760838  4330231
   9 │ Gyeongsangbuk-do    670963  1229173
  10 │ Gyeongsangnam-do    667404  1398804
  11 │ Incheon             409477  1050236
  12 │ Jeju                 95276   237196
  13 │ Jeollabuk-do          1221   854182
  14 │ Jeollanam-do          7869   934821
  15 │ Seoul              1973313  4776870
  16 │ Ulsan               167545   461354

## `寫入` 
```
CSV.write("Name.csv",df,delim='\t')
```

## `運算`

In [104]:
df = DataFrame(A=1:5,B=6:10)

5×2 DataFrame
 Row │ A      B     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      6
   2 │     2      7
   3 │     3      8
   4 │     4      9
   5 │     5     10

In [105]:
df[!,:"C=A+B"] = df[!,:A] .+ df[!,:B]
df[!,:"A+B"] = df[!,:A] .+ df[!,:B]

5-element Vector{Int64}:
  7
  9
 11
 13
 15

In [106]:
df

5×4 DataFrame
 Row │ A      B      C=A+B  A+B   
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      6      7      7
   2 │     2      7      9      9
   3 │     3      8     11     11
   4 │     4      9     13     13
   5 │     5     10     15     15

In [107]:
df[:,:D] = df[:,:A] .* df[:,:B]

5-element Vector{Int64}:
  6
 14
 24
 36
 50

In [108]:
df[:,:E] = df[:,:A] .<= df[:,:B]

5-element BitVector:
 1
 1
 1
 1
 1

In [109]:
df

5×6 DataFrame
 Row │ A      B      C=A+B  A+B    D      E    
     │ Int64  Int64  Int64  Int64  Int64  Bool 
─────┼─────────────────────────────────────────
   1 │     1      6      7      7      6  true
   2 │     2      7      9      9     14  true
   3 │     3      8     11     11     24  true
   4 │     4      9     13     13     36  true
   5 │     5     10     15     15     50  true

In [110]:
df[df[!,:A].<=3,:]

3×6 DataFrame
 Row │ A      B      C=A+B  A+B    D      E    
     │ Int64  Int64  Int64  Int64  Int64  Bool 
─────┼─────────────────────────────────────────
   1 │     1      6      7      7      6  true
   2 │     2      7      9      9     14  true
   3 │     3      8     11     11     24  true

In [111]:
f(x) =2x^2+x+1

f (generic function with 2 methods)

In [112]:
df[:,:F] = f.(df[:,:A])   # 函數應用

5-element Vector{Int64}:
  4
 11
 22
 37
 56

In [113]:
df

5×7 DataFrame
 Row │ A      B      C=A+B  A+B    D      E     F     
     │ Int64  Int64  Int64  Int64  Int64  Bool  Int64 
─────┼────────────────────────────────────────────────
   1 │     1      6      7      7      6  true      4
   2 │     2      7      9      9     14  true     11
   3 │     3      8     11     11     24  true     22
   4 │     4      9     13     13     36  true     37
   5 │     5     10     15     15     50  true     56

In [114]:
# 可以用 mapcols , 對整個 df 作 x.^2

mapcols(x->x.^2,df)

5×7 DataFrame
 Row │ A      B      C=A+B  A+B    D      E     F     
     │ Int64  Int64  Int64  Int64  Int64  Bool  Int64 
─────┼────────────────────────────────────────────────
   1 │     1     36     49     49     36  true     16
   2 │     4     49     81     81    196  true    121
   3 │     9     64    121    121    576  true    484
   4 │    16     81    169    169   1296  true   1369
   5 │    25    100    225    225   2500  true   3136

In [115]:
df

5×7 DataFrame
 Row │ A      B      C=A+B  A+B    D      E     F     
     │ Int64  Int64  Int64  Int64  Int64  Bool  Int64 
─────┼────────────────────────────────────────────────
   1 │     1      6      7      7      6  true      4
   2 │     2      7      9      9     14  true     11
   3 │     3      8     11     11     24  true     22
   4 │     4      9     13     13     36  true     37
   5 │     5     10     15     15     50  true     56

In [116]:
sort(df,:D,rev=true)

5×7 DataFrame
 Row │ A      B      C=A+B  A+B    D      E     F     
     │ Int64  Int64  Int64  Int64  Int64  Bool  Int64 
─────┼────────────────────────────────────────────────
   1 │     5     10     15     15     50  true     56
   2 │     4      9     13     13     36  true     37
   3 │     3      8     11     11     24  true     22
   4 │     2      7      9      9     14  true     11
   5 │     1      6      7      7      6  true      4

In [117]:
Matrix(df)  # DataFrame --> Matrix

5×7 Matrix{Int64}:
 1   6   7   7   6  1   4
 2   7   9   9  14  1  11
 3   8  11  11  24  1  22
 4   9  13  13  36  1  37
 5  10  15  15  50  1  56